<a href="https://colab.research.google.com/github/bpunar/Data-Science-Clarusway-/blob/main/Statistics_Assignment_2_D1491_Bekir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

In [ ]:
# D1491-Bekir

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import scipy as sp
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples =np.random.normal(100, 15, 1000)
samples

array([109.7010964 , 112.30973197, 109.94559156,  96.96764998,
        96.740637  , 102.66304153, 130.26939536,  90.68501936,
       117.30638294,  80.81743067,  80.46061253, 128.65815588,
        95.59902251,  88.13665318,  70.0100138 , 117.0130571 ,
        96.97312796, 101.01113007,  99.22583338,  96.37478214,
        96.17184056,  91.663618  , 124.23829528,  74.57598849,
       101.63421155, 132.47734808,  92.9803573 ,  99.53667685,
        98.85046245, 106.6872641 , 101.81885424,  91.16816445,
       110.25207871,  95.72935258,  91.99616815, 103.42156314,
       109.01573864,  94.67733545,  98.56569635, 103.76046629,
       112.45701008, 120.60468667,  82.24817945,  90.42776407,
       127.26408216,  89.58342415, 115.00636694, 112.05056049,
       104.16157174,  87.71287503, 113.24224874, 108.58642874,
        96.21555697, 115.05709436, 137.69599183,  67.54311946,
        78.07740025, 110.75312286,  79.49549088, 105.58080175,
        91.77811003, 100.57119889,  96.1906998 , 107.47

Compute the **mean**, **median**, and **mode**

In [ ]:
mean = np.mean(samples)
print("mean = ", mean)
median = np.median(samples)
print("median = ", median)
from scipy import stats
mode = stats.mode(samples)
print("mode =", mode)

mean =  100.41593686039604
median =  100.93979796291715
mode = ModeResult(mode=array([58.66102975]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)
print("Min değeri : ",  min)
max = np.max(samples)
print("max değeri :", max)
q1 = np.quantile(samples, 0.25)
print("Q1 değeri :", q1)
q3 = np.quantile(samples, 0.75)
print("Q3 değeri :" ,q3)
#iqr = q3- q1
iqr=stats.iqr(samples)
print("IQR değeri: ", iqr)


Min değeri :  58.66102975418439
max değeri : 147.61575730343316
Q1 değeri : 90.38760776453677
Q3 değeri : 110.53762681427878
IQR değeri:  20.150019049742014


Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
print("Varinace :", variance)
std_dev = np.std(samples)
print("standart sapma değeri : ", std_dev)

Varinace : 215.82496461079427
standart sapma değeri :  14.690982424970572


Compute the **skewness** and **kurtosis**

In [ ]:
import scipy as sp
skewness = sp.stats.skew(samples)
print("Skewness: ", skewness)
kurtosis = sp.stats.kurtosis(samples)
print("Kurtosis: ", kurtosis)

Skewness:  -0.08118566357513606
Kurtosis:  -0.21067564080009626


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([8,11,65,45,89,6,32,14,78,30])
print(y)
print(len(y))

[ 8 11 65 45 89  6 32 14 78 30]
10


Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r, p =stats.pearsonr(x, y)
print( "Correlation coefficient for x and y : ", r) 

Correlation coefficient for x and y :  0.17514721624983384


## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r, p = stats.pearsonr(x, y)
print("Pearson's r correlation is : ", r)

Pearson's r correlation is :  0.758640289091187


OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho, pval = stats.spearmanr(x, y)
print("Spearman's rho correlatiın : ", rho)

Spearman's rho correlatiın :  0.9757575757575757


## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn  as sns


Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
tips.corr("pearson")

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000